export const allWords = [
  { text: "agree", isCorrect: null },
  { text: "viable", isCorrect: null },
  { text: "whip", isCorrect: null },
  { text: "section", isCorrect: null },
  { text: "confuse", isCorrect: null },
  { text: "minority", isCorrect: null },
  { text: "house", isCorrect: null },
  { text: "investment", isCorrect: null },
  { text: "expand", isCorrect: null },
  { text: "object", isCorrect: null },
  { text: "professor", isCorrect: null },
  { text: "lot", isCorrect: null },
  { text: "race", isCorrect: null },
  { text: "lecture", isCorrect: null },
  { text: "fund", isCorrect: null },
  { text: "collapse", isCorrect: null },
  { text: "feature", isCorrect: null },
  { text: "maid", isCorrect: null },
  { text: "fun", isCorrect: null },
  { text: "rumor", isCorrect: null },
  { text: "birthday", isCorrect: null },
  { text: "colorful", isCorrect: null },
  { text: "chew", isCorrect: null },
  { text: "vote", isCorrect: null },
  { text: "kick", isCorrect: null },
  { text: "tip", isCorrect: null },
  { text: "station", isCorrect: null },
  { text: "general", isCorrect: null },
  { text: "market", isCorrect: null },
  { text: "pawn", isCorrect: null },
  //   { text: "consensus", isCorrect: null },
  //   { text: "theater", isCorrect: null },
  //   { text: "extort", isCorrect: null },
  //   { text: "constitution", isCorrect: null },
  //   { text: "wardrobe", isCorrect: null },
  //   { text: "earthquake", isCorrect: null },
  //   { text: "administration", isCorrect: null },
  //   { text: "opposed", isCorrect: null },
  //   { text: "multiply", isCorrect: null },
  //   { text: "engineer", isCorrect: null },
  //   { text: "accumulation", isCorrect: null },
  //   { text: "domination", isCorrect: null },
  //   { text: "proud", isCorrect: null },
  //   { text: "flight", isCorrect: null },
];
